  - name: install docker
    package:
      name:
      - docker
      state: present

  - name: Enable docker
    ansible.builtin.systemd:
      name: docker
      enabled: true

  - name: Start docker
    ansible.builtin.systemd:
      name: docker
      state: started

  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    register: file_exists

  - name: yum update
    yum:
      name: '*'
      state: latest
    when: file_exists.changed

  - name: Install java
    command: "sudo amazon-linux-extras install java-openjdk11 -y"

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Enable jenkins
    ansible.builtin.systemd:
      name: jenkins
      enabled: true

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

  - name: Add jenkins to docker group
    ansible.builtin.user:
      name: jenkins
      groups: docker
      append: yes
